tunnel: ${TUNNEL_ID}
credentials-file: /etc/cloudflared/${TUNNEL_ID}.json

ingress:
  - hostname: gps-map.online
    service: http://gps-web:3000
  - hostname: api.gps-map.online
    service: http://socket-service:4000
  - hostname: geo.gps-map.online
    service: http://map_server:8080
  - hostname: emqx.gps-map.online
    service: http://emqx:18083
  - service: http_status:404